### PR TITLE
korean translation of the readme document

### PR DESCRIPTION
**Pull request by choiyongwoo**
Hello, I translated readme document into korean to make a translation. I'll help you one by one. Please merge this first. thank you very much.

### CODE REVIEW

**Comment by ice1000** [comment]
Is the file UTF-8?

**Comment by choiyongwoo** [comment]
yes, I'll change it to an md file. Please merge it. thank you.

**Comment by ice1000** [comment]
Why closing?

**Comment by choiyongwoo** [comment]
Yes, I converted it back into an md file. I want you to merge it. Thank you.
-----Original Message-----

**Pull request closed without merging**
